version: "3.8"

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    tty: true
    volumes:
      - ./db_data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always
    env_file:
      - ${PWD}/.env/mariadb.env

  phpmyadmin:
    container_name: phpadmin
    tty: true
    links:
      - mariadb
    depends_on:
      - mariadb
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    env_file:
      - ${PWD}/.env/mariadb.env
      - ${PWD}/.env/phpadmin.env

  maildev:
    container_name: maildev
    image: maildev/maildev
    tty: true
    restart: always
    env_file:
      - ${PWD}/.env/maildev.env
    ports:
      - "1080:1080"
      - "1025:1025"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    image: wordpress:6.4.2-php8.1-apache
    restart: always
    ports:
      - "8000:80"
    env_file:
      - ${PWD}/.env/mariadb.env
      - ${PWD}/.env/phpadmin.env
      - ${PWD}/.env/wordpress.env

    volumes:
      - ${PWD}/wordpress/:/var/www/html

volumes:
  db_data:
